### ISSUE TITLE
Strange results on Hugging Face

### ISSUE THREAD

**Issue by joansc** [fhamborg/NewsMTSC#15]
Hello!

I am testing your model uploaded on Hugging Face( roberta-targeted-sentiment-classification-newsarticles) and its giving some strange results. Just from inputting text on the example text box I get:

_Two children among 3 Eritrean refugees killed in Tigray air raid._ - LABEL_0=0.53   LABEL_1=0.47
_Gunfire heard as BBC visits scene of Kazakh clashes._ - LABEL_0=0.539   LABEL_1=0.461
_Trinity College Dublin begins €90m project to relocate vulnerable books_ - LABEL_0=0.506   LABEL_1=0.494
_US economy added 199,000 new jobs in December as unemployment rate drops_ - LABEL_0=0.506   LABEL_1=0.494

If I use transformers with my own python code `sentiment_analysis = pipeline("sentiment-analysis", model=folder, tokenizer=folder, return_all_scores=True)`, I get slightly different results:

_Two children among 3 Eritrean refugees killed in Tigray air raid._ - LABEL_0=0.59   LABEL_1=0.41
_Gunfire heard as BBC visits scene of Kazakh clashes._ - LABEL_0=0.6   LABEL_1=0.39
_Trinity College Dublin begins €90m project to relocate vulnerable books_ - LABEL_0=0.59   LABEL_1=0.40
_US economy added 199,000 new jobs in December as unemployment rate drops_ - LABEL_0=0.59   LABEL_1=0.41

I assume LABEL_0 corresponds the proability the sentence is negative in sentiment...? Anyway, I do not see relevant results from the model on both cases and I am wondering if it's because I am missing something.

Thanks and keep up with the amazing work!

Joan

**Comment by fhamborg** [comment]
Hi, yea, something's weird with the model on HF, and I think one reason for that is that their API does not allow to pass the  inputs required for the model (one being the input sentence, the others being the information where the target starts and ends within that sentence). I opened an issue at HF to enable and share custom pipelines (https://github.com/huggingface/transformers/issues/14785) but until this issue is fixed I assume one cannot really use the model with HF. Instead I recommend to use https://pypi.org/project/NewsSentiment/

**Comment by joansc** [comment]
Got it, I'll try the other way then! Thanks for the fast response!

**Comment by fhamborg** [comment]
updated the description on HF hub to highlight that users should use the pypi package
